bce-iot-10555: modbus module
baetyl/baetyl-adapter pull request #1
Opened 2019-10-24 05:55 UTC by xiejingru

2019-10-24 07:29 UTC, ludanfeng requested changes

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/Dockerfile
> +ENTRYPOINT ["baetyl-modbus"]
baetyl-adapter-modbus

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/client.go
> +	rtuHandler *modbus.RTUClientHandler
抽象成新的interface，包含Connect()和Close()

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/client.go
> +		err := h.Connect()
newClient总是成功返回，要有重连的机制，read失败要能重连
测一下如果没有connect就read会发生什么？panic还是return error

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/client.go
> +	quantity := item.Quantity
移除

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/client.go
> +		return reader.read(cli.mbClient, address, quantity)
考虑一下重连机制

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/client.go
> +		return nil, fmt.Errorf("function code (%d) not supported", item.Function)
不要在运行中检查，配置中设置好约束

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/config.go
> +	Function byte `yaml:"function" json:"function"`
设置一下约束

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/config.go
> +		RxDuringTx bool `yaml:"Rx_during_tx" json:"Rx_during_tx"`
rx_during_tx

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/config.go
> +	SlaveID byte `yaml:"slave_id" json:"slave_id"`
slave_id --> slaveid

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/config.go
> +	ParseItems []ParseItem `yaml:"parse_items" json:"parse_items"`
ParseItems --> Maps ?

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/config.go
> +
刚才说过了，移除

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/config.go
> +	Publish *Publish `yaml:"publish" json:"publish"`
所以还是只支持一个主题？

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/main.go
> +		sender := newSender(mqttCli, msgChan)
mqtt client内部有一个channel，msgChan有必要吗？

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/main.go
> +			err = mqttCli.Close()
就近原则，mqttclient创建成功后马上defer mqttCli.Close()

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/main.go
> +		pq := make(PriorityQueue, 0)
之前说了，有多少个interval就启动多少个ticker，串行读取就行了

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/pq.go
> +// A PriorityQueue implements heap.Interface and holds task.
太复杂了，移掉吧

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/reader.go
> +}
这个也设计复杂了，设计成面向对象

2019-10-24 07:29 UTC, ludanfeng commented on baetyl-modbus/task.go
> +	results, err := t.mbCli.read(t.parseItem)
有没有可能预分配byte array，然后边从串口读边写入byte array

2019-10-24 07:33 UTC, ludanfeng requested changes

2019-10-24 07:33 UTC, ludanfeng commented on baetyl-modbus/task.go
> +	t.msgChan <- pkt
直接用mqttclient send

2019-10-24 08:59 UTC, xiejingru commented on baetyl-modbus/config.go
> +	Publish *Publish `yaml:"publish" json:"publish"`
是的，考虑到兼容物解析，也是发送到一个主题

2019-10-28 12:27 UTC, ludanfeng requested changes

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/Dockerfile
> +ARG MODULE=baetyl-modbus
baetyl-modbus -> baetyl-adapter-modbus
全都替换啊，另外这个文件是生成的不要手动改

参考 https://github.com/baetyl/baetyl/blob/master/sdk/baetyl-go/generate.go

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/Makefile
> +# Code generated by github.com/baetyl/baetyl/sdk/baetyl-go/generate.go. DO NOT EDIT.
这个文件也是生成的

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/client.go
> +func NewClient(cfg SlaveItem) *MbClient {
移到MbClient struct定义的后面
SlaveItem改成SlaveConfig吧

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/client.go
> +		return fmt.Errorf("failed to close tcp client: %s", err.Error())
return fmt.Errorf("failed to close client: %s", err.Error())

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/mb_mock.go
> +type MbSlave struct {
放到测试里，比如 slave_test.go，否着成产品代码了

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	Tables []MapItem `yaml:"tables" json:"tables"`
Maps []MapConfig `yaml:"maps" json:"maps"`  ?

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	Publish *Publish `yaml:"publish" json:"publish" validate:"nonnil"`
Publish Publish `yaml:"publish" json:"publish"` ?

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
> +			client.Connect()
打印一下错误日志

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
> +			client := NewClient(slaveItem)
slave和clients是一对一的吧？是的话不把clients放进slave吗？

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
> +		for _, item := range cfg.Tables {
不是一个table一个ticker，是一种采样间隔一个ticker
先按照采样间隔分桶，同一个桶里的read串行执行

2019-10-28 12:27 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
> +
定义一个 module struct，复杂度增加了，不适合在main里展开了
type mb struct {
}

2019-10-28 12:31 UTC, ludanfeng requested changes

2019-10-28 12:31 UTC, ludanfeng commented on baetyl-adapter-modbus/map.go
> +		return nil, err
重连的错误日志打印一下
如果重连成功，再读一次

2019-10-30 06:51 UTC, ludanfeng requested changes

2019-10-30 06:51 UTC, ludanfeng commented on baetyl-adapter-modbus/README.md
> +    interval: 3s
采样周期通常是针对slave的还是采样点的？

2019-10-30 06:51 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	// slave.go list
slave list

2019-10-30 06:51 UTC, ludanfeng commented on baetyl-adapter-modbus/map.go
> +		return nil, err
if err2 == nil {
			return m.r(m.cfg.Address, m.cfg.Quantity)
		}
		m.log.WithField("slave", m.cfg.SlaveID).Errorf("failed to reconnect: %s", err2.Error())
		return nil, err

2019-10-30 06:51 UTC, ludanfeng commented on baetyl-adapter-modbus/mb.go
> +func Package(ma *Map) ([]byte, error){
怎么不跟Map的定义放一起？不应该是：func (ma *Map)Package() ([]byte, error){ 吗？

2019-10-30 06:51 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +		m := NewMap(mapConfig, slaves[mapConfig.SlaveID], logger.WithField("modbus", "map"))
这个WithField("modbus", "map")没有区分度

2019-10-30 06:51 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +					err := m.Execute(mod.mqttCli, mod.cfg.Publish)
永远不会退出？你用baetyl把这个模块起来试试，是不是总是超时才推出？

2019-10-30 07:10 UTC, xiejingru commented on baetyl-adapter-modbus/modbus.go
> +					err := m.Execute(mod.mqttCli, mod.cfg.Publish)
会直接退出
main退出后，这里的启动的routine都会直接停止

2019-10-31 04:58 UTC, ludanfeng requested changes

2019-10-31 04:58 UTC, ludanfeng commented on baetyl-adapter-modbus/mb.go
> +		err = mqttCli.Send(pkt)
这里有个优化点，mqtt client内部的send channel长度最好是采集点数的两倍，避免串行采集被send block

2019-10-31 04:58 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +					err := m.Execute(mod.mqttCli, mod.cfg.Publish)
没有优雅退出吧

2019-11-01 02:25 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
> +		ctx.Config().Hub.BufferSize = len(cfg.Maps) * 2
if ctx.Config().Hub.BufferSize < len(cfg.Maps) * 2 {
ctx.Config().Hub.BufferSize = len(cfg.Maps) * 2
}

2019-11-01 02:25 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
>  		return nil
return modbus.Close()

2019-11-01 02:25 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +			defer wg.Done()
往上移动两行，资源回收完毕再退出

2019-11-01 02:38 UTC, ludanfeng requested changes

2019-11-01 02:38 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +			return err
其他的slave还是要关一下的，error汇总后一起返回

2019-11-01 06:32 UTC, ludanfeng requested changes

2019-11-01 06:32 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
>  	return nil
var msg string
	for _, slave := range mod.slaves {
		if err := slave.client.Close(); err != nil {
			mod.log.Warnf("failed to close slave id=%d: %s", slave.cfg.ID, err.Error())
			msg += ";" + err.Error()
		}
	}
	if msg != "" {
		return fmt.Errorf("failed to close slaves: %s", msg)
	}
	return nil

2019-11-01 06:49 UTC, ludanfeng approved these changes

2019-11-01 06:58 UTC, merged