baetyl-17: add parse
baetyl/baetyl-adapter pull request #2
Opened 2020-05-08 12:13 UTC by xiejingru

2020-05-09 03:17 UTC, ludanfeng requested changes

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	Kind     string        `yaml:"kind" json:"kind" validate:"regexp=^(binary|json)?$" default:"json"`
Kind改成Format或者Encoding吧。
另外注意一下所有默认值，需要支持无配置也能正常运行。

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	Type      string `yaml:"type" json:"type" validate:"regexp=^(long|string)?$" default:"long"`
long改成integer，如果Job的发送格式是binary，time的type只能是integer
Time应该是一个特殊的Field
type Time struct {
Field
Format string
Precision string
}

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	Interval time.Duration `yaml:"interval" json:"interval" default:"5s" validate:"nonzero"`
有default就不会出现nonzero，validate:"nonzero 可以移除

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	Precision string `yaml:"precision" json:"precision" default:"second"`
没有validate？
用缩写吧，这几个单词不好拼。s|ms|ns

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/config.go
> +	Field *Field `yaml:"field" json:"field"`
没必要加指针吧，尽量减少指针判空逻辑，panic都是此类问题引发

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/constants.go
> +	Float64 = "float64"
用枚举归好类

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
> +			mqttConfig.ClientID = uuid.NewV4().String()
建议用ctx.ServiceName()作为client id

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
>  		modbus.Start(ctx)
这三行合并吧，NewModbus直接启动。另外mqtt/http client不让Modbus内部自己选择初始化吗?
modbus := NewModbus(ctx，cfg) // 因为Start已经传了ctx

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/map.go
> +	}
配置检查和初始化要尽早，并且可以在反序列化的时候统一检查和处理

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/map.go
>  	}
populateQuantityIfNeeds(cfg *mc) {  // 这里倒是建议用指针，外面确保传入非nil
        ...
	switch cfg.Field.Type {
	case Bool,Int16, UInt16:
		cfg.Quantity = 1
	....
	}

2020-05-09 03:17 UTC, ludanfeng commented on baetyl-adapter-modbus/map.go
> +func (m *Map) Parse() (interface{}, error) {
Collect和Parse重新整理吧，逻辑有点混乱。
不管binary还是json，步骤都是先Read（直接读成binary输出的格式），后Parse（如果需要解析成json把Read的输出解析成json），最后发送出去

2020-05-10 15:07 UTC, ludanfeng requested changes

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/constants.go
> +	IntegerTime = "long"
long --> integer

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +			err := w.Execute(mod.cfg.Publish)
加个TODO：job都是独立的，可以有自己的输出，可以有默认的输出主题比如：<service_name>/<slave_id>

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +	wg     *sync.WaitGroup
不要用指针，golang的struct都在自己会初始化的，不用赋值

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
> +		wg:     new(sync.WaitGroup),
这行移除

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/modbus.go
>  		return fmt.Errorf("failed to close slaves: %s", strings.Join(msgs, ";"))
资源没有清理完，不要提早退出

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/main.go
> +		if err := validate(cfg); err != nil {
LoadCustomConfig里面已经做类setDefault和validate的操作，没想到你又搞一套，follow LoadCustomConfig内部的setDefault和validate约定实现一下，设置默认值和检查的逻辑就可以了

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/utils.go
> +			if job.Encoding == JsonEncoding {
实现一下Job的反序列化就可以了

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/utils.go
> +func validate(cfg Config) error {
实现一个validate tag的方法，比如叫checkSlaves

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/utils.go
> +				if m.Field.Name == "" || m.Field.Type == "" {
实现一个validate tag的方法，比如叫checkEncoding

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/worker.go
> +	}
移到获取时间的逻辑的后面

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/worker.go
> +		pld = append(pld, w.job.SlaveId)
SlaveId和timestemp不应该在最前面吗？注释一下定义的格式，binary packet建议把头定义好，比如
|------------------------------ head ---------------------------------|---data---|
|----timestemp----|-slaveid-|---none---|---address---|---quantity---|---data---|
-0-1-2-3-4-5-6-7------8-----9-10-11---12-13-14-15---16-17-18-19--- ....

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/worker.go
>  			if w.job.Time.Format != "" {
不会出现w.job.Time.Format==""，有默认值

2020-05-10 15:07 UTC, ludanfeng commented on baetyl-adapter-modbus/worker.go
> +			Attributes: attr,
建议不要搞两层结构了。把time、slave、address、quantity规定系统字段，防止用户使用就可以了，field.name的validate tag加一下

2020-05-11 13:49 UTC, ludanfeng requested changes

2020-05-11 13:49 UTC, ludanfeng commented on modbus/main.go
> +	validator.SetValidationFunc("validjobs", validateJobs)
移到config.go里

2020-05-11 13:49 UTC, ludanfeng commented on modbus/main.go
> +		setDefault(&cfg)
这个还需要吗？

2020-05-11 13:49 UTC, ludanfeng commented on modbus/utils.go
> +		if job.Time.Name == "" {
有default tag啊，怎么还要这里设置？

2020-05-11 13:49 UTC, ludanfeng commented on modbus/utils.go
> +func validateJobs(v interface{}, param string) error {
移到config.go里，这个是业务相关的，不推荐放到utils里。utils放的都是通用工具。

2020-05-11 13:49 UTC, ludanfeng commented on modbus/utils.go
> +	}
推荐下面的写法，先处理异常，后走happy path
if xxx {
  return xxx
}

// happy path

2020-05-11 13:49 UTC, ludanfeng commented on modbus/worker.go
> +		pld = append(pld, sp...)
pld = make([]byte, 12)
binary.BigEndian.PutUint64(pld, uint64(ts))
pld[8]=w.job.SlaveId

2020-05-11 13:49 UTC, ludanfeng commented on modbus/worker.go
>  	}
ts的逻辑只有BinaryEncoding用到，移到if w.job.Encoding == BinaryEncoding {}里

2020-05-11 14:00 UTC, ludanfeng requested changes

2020-05-11 14:00 UTC, ludanfeng commented on modbus/modbus.go
> +			msgs = append(msgs, err.Error())
这里直接逐条打印warn日志就行，不用收集后一次性打印

2020-05-12 04:01 UTC, xiejingru commented on modbus/worker.go
>  	}
JsonEncoding也用了

2020-05-12 04:53 UTC, xiejingru commented on modbus/utils.go
> +		if job.Time.Name == "" {
[]Jobs自定义Defaults无效

2020-05-12 05:21 UTC, ludanfeng requested changes

2020-05-12 05:21 UTC, ludanfeng commented on modbus/config.go
> +	}
移除，直接 v.([]Job) 判断是否 ok 就行

2020-05-12 05:21 UTC, ludanfeng commented on modbus/config.go
> +				return fmt.Errorf("can not define sys field name: %s", m.Field.Name)
please use another name, '%s' is reserved by the system

2020-05-12 05:21 UTC, ludanfeng commented on modbus/config.go
> +func (t *Time) SetDefaults() {
用 default tag，不知道怎么用可以问一下，不要保持现状。

Time     Time          `yaml:"time" json:"time" default:"{\"name\":\"time\", ...}"`

2020-05-12 05:21 UTC, ludanfeng commented on modbus/modbus.go
> +		mod.logger.Error("failed to close slave", log.Any("slave id", slave.cfg.ID))
Error --> Warn 
Close里的error一般用warn，影响不大

2020-05-12 05:21 UTC, ludanfeng commented on modbus/utils.go
>  func setDefault(cfg *Config) {
业务配置逻辑不适合方utils，utils里放的工具业务无关，移到config.go
setDefault 还是没用上 default 框架，再说吧

2020-05-12 09:16 UTC, ludanfeng requested changes

2020-05-12 09:16 UTC, ludanfeng commented on modbus/go.sum
> +github.com/baetyl/baetyl-adapter v0.0.0-20191226100116-d8a4e21f49eb h1:BMUvYb/6oeetzTCBlsGvctITOKr0tRZw8mwkF2kcBOY=
怎么还会引入自己？

2020-05-12 09:16 UTC, ludanfeng commented on modbus/modbus.go
> +	sender := mqttSender{publish: cfg.Publish, Client: mqtt.NewClient(*option)}
抽象的作用就是为了modbus不再依赖mqtt，所以抽象后，sander就应该是传进来的
否着下面的这段代码还是没发覆盖测试吧？

2020-05-12 09:16 UTC, ludanfeng commented on modbus/modbus.go
> +		mod.logger.Warn("failed to close slave", log.Any("slave id", slave.cfg.ID))
slave.Close()去哪了？

2020-05-12 09:16 UTC, ludanfeng commented on modbus/modbus.go
> +	return mod.sender.Close()
如果sender是传入的，就不需要modbus来close了

2020-05-12 09:21 UTC, ludanfeng requested changes

2020-05-12 09:21 UTC, ludanfeng commented on modbus/constants.go
> +var SysType map[string]struct{}
var SysType = map[string]struct{}{
		Bool: {},
		Int16: {},
		UInt16: {},
		Int32: {},
		UInt32: {},
		Int64: {},
		UInt64: {},
		Float32: {},
		Float64: {},
	}

2020-05-12 09:58 UTC, ludanfeng requested changes

2020-05-12 09:58 UTC, ludanfeng commented on modbus/modbus.go
> +			ctx.Log().Error("failed to connect slave id=%d: %s", log.Any("id", slaveConfig.ID), log.Error(err))
"failed to connect slave id=%d: %s" --> "failed to connect slave"
这个日志框架不用fmt，采用log.Field附加信息

2020-05-12 09:58 UTC, ludanfeng commented on modbus/modbus.go
> +			w := NewWorker(job, slave, sender, log.With(log.Any("modbus", "map point")))
w := NewWorker(job, slave, sender, log.With(log.Any("slaveid", job.SlaveId)))
Worker 内部打印日志就不用每次追加slaveid信息了

2020-05-12 12:03 UTC, ludanfeng approved these changes

2020-05-14 05:35 UTC, merged