support writing data
baetyl/baetyl-adapter pull request #6
Opened 2020-08-24 03:50 UTC by xiejingru

2020-08-24 06:08 UTC, ludanfeng requested changes

2020-08-24 06:08 UTC, ludanfeng commented on go.mod
> +	github.com/baetyl/baetyl-go v0.1.92
?

2020-08-24 06:08 UTC, ludanfeng commented on modbus/config.go
> +	Method string `yaml:"method" json:"method" validate:"regexp=(tcp|rtu)" default:"rtu"`
没找到用这个字段的地方

2020-08-24 06:08 UTC, ludanfeng commented on modbus/modbus.go
> +	mqttCfg := ctx.SystemConfig().Broker
可以用最新的sdk的方法创建默认的mqtt client了，会自动订阅$link/<service-name>以及加载内部证书

2020-08-24 11:51 UTC, xiejingru commented on modbus/modbus.go
> +	mqttCfg := ctx.SystemConfig().Broker
没有在baetyl framework下运行

2020-08-26 04:50 UTC, ludanfeng commented on modbus/client.go
> +	switch cfg.Method {
我看到有些产品把tcp/rtu选项叫做mode，尽量采用广泛使用的命名

2020-08-26 04:50 UTC, ludanfeng commented on modbus/README.md
>          address: 40011 # 起始地址
可以按照最新的设计更新一版readme了

2020-08-26 11:36 UTC, ludanfeng approved these changes

2020-08-26 11:36 UTC, ludanfeng commented on cmd/modbus/Makefile
> +GO_FLAGS?=-ldflags '-X "github.com/baetyl/baetyl-go/v2/utils.REVISION=$(GIT_REV)" -X "github.com/baetyl/baetyl-go/utils.VERSION=$(VERSION)"'
第二个-X没加v2

2020-08-27 05:50 UTC, merged